name:                apisher
version:             0.1.0.0
github:              "Ordluks/apisher"
license:             GPL-3.0-only
author:              "Ordluks"
maintainer:          "wifi355s31@gmail.com"
copyright:           "2025 Yakov Basaranovich"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Library for fast creation you light-weight TCP-based server API
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Ordluks/apisher#readme>

dependencies:
- base >= 4.7 && < 5
- network >= 3.1.4.0
- cereal >= 0.5.8.3
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  apisher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - apisher
    - network-run
